//@prepros-append pages/common.js
//@prepros-append pages/validation.js
//@prepros-append pages/maps.js
//@prepros-append pages/popup.js
//@prepros-append pages/sliders.js
//@prepros-append pages/index.js
//@prepros-append pages/catalog.js
//@prepros-append pages/product.js
//@prepros-append pages/articles.js
//@prepros-append pages/cabinet.js
//@prepros-append pages/reviews.js
//@prepros-append pages/feed.js
//@prepros-append pages/compare.js
//@prepros-append pages/cart.js